export const IPC = {
  getData: 'pt:getData',
  addTask: 'pt:addTask',
  updateTask: 'pt:updateTask',
  deleteTask: 'pt:deleteTask',
  tickTask: 'pt:tickTask',
  untickTask: 'pt:untickTask',
  reorderActive: 'pt:reorderActive',
  archiveCompleted: 'pt:archiveCompleted',
  archiveOne: 'pt:archiveOne',
  deleteArchived: 'pt:deleteArchived',
  clearArchive: 'pt:clearArchive',
  restoreArchived: 'pt:restoreArchived',
  setCompletedAt: 'pt:setCompletedAt',
  setSettings: 'pt:setSettings',
  showMain: 'pt:showMain',
  isPackaged: 'pt:isPackaged',
  windowMinimize: 'pt:window:minimize',
  windowMaximizeToggle: 'pt:window:maximize-toggle',
  windowClose: 'pt:window:close',
  windowIsMaximized: 'pt:window:is-maximized',
  overlayHide: 'pt:overlay:hide',
  overlayResize: 'pt:overlay:resize',
  data: 'pt:data',
  maximized: 'pt:window:maximized'
} as const
